### ISSUE TITLE
config files could not read in scan

### ISSUE THREAD

**Issue by Vasanth3g** [Comcast/Superior-Cache-ANalyzer#20]
```
Error in config file - cache not found: [Errno 20] Not a directory: '/opt/trafficserver/etc/trafficserver/storage.config/records.config'
Choose an option (or option number)

[1] Read Storage config

(option, or use ^C or ^D to quit):
```

**Comment by ocket8888** [comment]
Can you paste the output of `sudo scan --tgm --debug -D -c /opt/trafficserver/etc/trafficserver/` ?

**Comment by Vasanth3g** [comment]
DEBUG: 'utils' module: Loaded
DEBUG: 		POINTER_SIZE: 8
DEBUG: 'directory' module: Loaded
DEBUG: 		DirEntry size: 10
DEBUG: 		Doc size: 72
DEBUG: 'stripe' module: Loaded
DEBUG: 		Span Block Header size: 24
DEBUG: 		Stripe (metadata) size: 72
DEBUG: 'span' module: Loaded
DEBUG: 		DiskHeader size: 32
DEBUG: 'config' module: Loaded
DEBUG: main: Starting scan version 3.3.6 with args: Namespace(config_dir='/opt/trafficserver/etc/trafficserver/storage.config', debug=True, dump=False, dump_breakdown=None, fips=False, loadavg=None, tgm=True, version=False)
DEBUG: config.init: reading configuration files from /opt/trafficserver/etc/trafficserver/storage.config/
DEBUG: readRecordConfig: opening file /opt/trafficserver/etc/trafficserver/storage.config/records.config for reading
DEBUG: Traceback (most recent call last):
DEBUG:	  File "/usr/lib/python3.6/site-packages/scan/__init__.py", line 181, in main
DEBUG:	    config.init(confDir)
DEBUG:	  File "/usr/lib/python3.6/site-packages/scan/config.py", line 179, in init
DEBUG:	    num = readRecordConfig()
DEBUG:	  File "/usr/lib/python3.6/site-packages/scan/config.py", line 254, in readRecordConfig
DEBUG:	    with open(fname) as file:
DEBUG:	NotADirectoryError: [Errno 20] Not a directory: '/opt/trafficserver/etc/trafficserver/storage.config/records.config'
DEBUG:	
Unable to scan cache: '[Errno 20] Not a directory: '/opt/trafficserver/etc/trafficserver/storage.config/records.config''

**Comment by ocket8888** [comment]
It appears that you gave it a path to the actual `storage.config` file. What you should do is give it the path to the _directory that **contains**_ your `storage.config`, `records.config` etc. In this case it looks like that's `/opt/trafficserver/etc/trafficserver/`.
